---
- hosts: ec2_jenkins_server
  name: Setup and Configure Jenkins Server
  become: yes
  vars:
    jenkins_user: jenkins
    jenkins_group: jenkins
    jenkins_home: /var/lib/jenkins
    ssm_password_name: "/jenkins/admin_password"

  tasks:
    - name: Update all system packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install required dependencies
      yum:
        name: ['git', 'java-21-amazon-corretto-devel', 'docker', 'ansible', 'aws-cli']
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Import Jenkins GPG key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins-stable
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: installed

    - name: Ensure Jenkins is stopped and disabled before configuration
      service:
        name: jenkins
        state: stopped
        enabled: no

    - name: Create systemd override directory for Jenkins service
      file:
        path: /etc/systemd/system/jenkins.service.d
        state: directory

    - name: Create systemd override file to disable setup wizard and set JCasC path
      blockinfile:
        path: /etc/systemd/system/jenkins.service.d/override.conf
        create: yes
        block: |
          [Service]
          Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dcasc.jenkins.config={{ jenkins_home }}/casc_configs"

    - name: Add the jenkins user to the docker group
      user:
        name: "{{ jenkins_user }}"
        groups: docker
        append: yes

    - name: Create directories for JCasC configs
      file:
        path: "{{ jenkins_home }}/casc_configs"
        state: directory
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_group }}"
        mode: '0755'

    - name: Copy plugins.txt file for installation
      copy:
        src: ../../jenkins/config/plugins.txt
        dest: "{{ jenkins_home }}/plugins.txt"
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_group }}"

    - name: Download Jenkins Plugin Installation Manager
      get_url:
        url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.13.2/jenkins-plugin-manager-2.13.2.jar
        dest: /opt/jenkins-plugin-cli.jar
        mode: '0755'

    - name: Install all plugins from plugins.txt before first start
      command: >
        java -jar /opt/jenkins-plugin-cli.jar
        --plugin-file {{ jenkins_home }}/plugins.txt
        --plugin-download-directory {{ jenkins_home }}/plugins
      changed_when: true
      become_user: "{{ jenkins_user }}"

    - name: Retrieve Jenkins admin password from AWS SSM
      command: aws ssm get-parameter --name "{{ ssm_password_name }}" --with-decryption --query "Parameter.Value" --output text
      register: jenkins_password_from_ssm
      become_user: ec2-user
      no_log: true

    - name: Copy JCasC configuration files
      template:
        src: "{{ item.src }}"
        dest: "{{ jenkins_home }}/casc_configs/{{ item.dest }}"
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_group }}"
      loop:
        - { src: '../../jenkins/config/jenkins.casc.yml', dest: '01-main.casc.yml' }
        - { src: '../../jenkins/config/prometheus.casc.yml', dest: '02-prometheus.casc.yml' }
        - { src: '../../jenkins/config/nodes.casc.yml', dest: '03-nodes.casc.yml' }
        - { src: '../../jenkins/config/job.casc.yml', dest: '04-jobs.casc.yml' }
      vars:
        jenkinsAdminPassword: "{{ jenkins_password_from_ssm.stdout }}"
      no_log: true

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to be accessible
      uri:
        url: http://localhost:8080/login
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 20
