jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Administrator"
          password: "{{ jenkinsAdminPassword }}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
